### ISSUE TITLE
Change height

### ISSUE THREAD

**Issue by Arsham-rmz** [dotswan/filament-map-picker#14]
how can i change the height of map ?!

**Comment by mohaphez** [comment]
Hi @Arsham-rmz 

Currently, it is not possible to edit the style, we will add this possibility soon.

**Comment by mohaphez** [comment]
The `extraStyles([])` option enhances the plugin, allowing you to incorporate your own custom style rules for the map field.

Should you have any further suggestions, please do not hesitate to inform us. We warmly welcome them.

Thanks,
