### ISSUE TITLE
Maps not working at first load

### ISSUE THREAD

**Issue by ivankrister** [dotswan/filament-map-picker#19]
At first visit on page the maps not working but after refresh its maps load and work

**Comment by mohaphez** [comment]
Hi @ivankrister 

Are you use spa mode ?  
Have any errors in console log ? 
you just can not see map layers ? or  ca not see map section box(buttons,..) in first load even ?

**Comment by ivankrister** [comment]
I dont see some sort of error related to the maps when its fail to load or not working but if its load i see an error in console

NOT WORKING in first load of page
![image](https://github.com/dotswan/filament-map-picker/assets/55677686/93051f9d-ed2d-4d0c-bce4-2bcca2a22089)

WORKING AFTER REFRESH

![image](https://github.com/dotswan/filament-map-picker/assets/55677686/d5dd4bc2-6734-4f19-ac7d-140d98363cd0)

by the way how to set a default lat lng in the maps?

**Comment by SWEET1S** [comment]
+ same

**Comment by mohaphez** [comment]
Hi everybody 

I would be grateful if you could send me the answers to these few questions

What is the package version?
What is the filament version?
Have you activated the spa mode of the panel?

also if you attach some codes will be great too.

**Comment by SWEET1S** [comment]
Hello, I found the problem. The height of map need to be lower then 100vh. By default in documentation wroten with min-height: 150vh

**Comment by taher-k5** [comment]
> Hello, I found the problem. The height of map need to be lower then 100vh. By default in documentation wroten with min-height: 150vh

Thanks mate

**Comment by Saifallak** [comment]
same too filament v3 
package v1.8.8

**Comment by Saifallak** [comment]
disabling SPA solves the issue, but it's not ideal solution,
