### ISSUE TITLE
Map location search form

### ISSUE THREAD

**Issue by jorelart** [dotswan/filament-map-picker#20]
Is it possible to add search form on the map? Or maybe I didn't know it already existed.

**Comment by jorelart** [comment]
@mohaphez Thank you for the advice.

the package went well as expected, till I found a little difficulty when choosing an unfamiliar location and it should be easier when I can search using keywords.

Hopefully this feature can be included later.

So should I close this issue?

**Comment by mohaphez** [comment]
I am glad that this package met your needs 
I'll definitely put the mentioned feature in the list of future features. 

Thank you.
