### ISSUE TITLE
Map dont set value on draggrable on false

### ISSUE THREAD

**Issue by octaviogamero27** [dotswan/filament-map-picker#26]
When the map loads and draggrable is false, the map doesnt set value of LiveLocation

**Comment by mohaphez** [comment]
Hi @octaviogamero27 

When draggable is set to false, what trigger should the liveLocation feature use to receive and share the location live? Isn't the liveLocation feature essentially meaningless without draggable?

**Comment by enriquemdev** [comment]
Isnt this solved yet?

**Comment by mohaphez** [comment]
Hi 

To clarify, the liveLocation function dynamically updates the location by capturing it from the map in real-time as the marker is dragged and dropped. This updated location is then sent to the Livewire component, allowing the lat and lng fields to be updated live.

Based on your description:

You need the map to be read-only, while the browser periodically (e.g: every 10 seconds) retrieves the user’s location, encodes it, and updates the lat and lng fields. Is that correct?

**Comment by enriquemdev** [comment]
Hi there, thanks for the quick response!

That would be perfect!
And even if the location is obtained only at initial render it would be
enough. (plus being readonly).

If you can make location updates periodically as you say, even better!

Feel free to tell me if you want me to help in implementation, i am more
than willing!

King regards.
