### ISSUE TITLE
Map not properly showing when sticky footer is used

### ISSUE THREAD

**Issue by Jamerze** [dotswan/filament-map-picker#28]
Hello,

For my filamentphp app I just started implementing your Map picker, and I really like the functionalities it has. Thanks for providing this plugin!

In my application I use an EditAction that opens a form with a slide over. When implementing the map in this form, I noticed it didn't work well with the sticky footer that is automatically enabled for slide overs (as can be seen in the image below), because it is showed in front of the buttons. This problem only occurs when the sticky footer is present (also when you use the modal and combine it with ->stickyModalFooter()).

![Screenshot 2024-08-07 090349](https://github.com/user-attachments/assets/d0cdd6d2-47d6-458b-b5d8-ac965fcb694e)

**Comment by Jamerze** [comment]
I just checked the code and noticed that it is because of the z-index in resources\views\fields\osm-map-picker.blade.php. Currently it is set to 1, but setting it to 0 seems to fix the issue.

**Comment by mohaphez** [comment]
Hi @Jamerze 
i am glad the plugin is useful to you and you can fix the issue by extraStyles method ,
if any other thing you need ,Please do not hesitate to inform us.
