### ISSUE TITLE
My Location Button

### ISSUE THREAD

**Issue by saelco** [dotswan/filament-map-picker#3]
Can I use "my location" button to ensure my current location? If it can be done, it would be very helpful.

**Comment by mohaphez** [comment]
Dear @saelco,

It's a great idea! I've worked on it and will be adding it to #5  .

Should you have any further suggestions, please do not hesitate to inform us. We warmly welcome them.

Thanks,

**Comment by saelco** [comment]
It was so great. Thank for your response. I’ll wait for the release.
