### ISSUE TITLE
Extend leaflet with geoman plugin

### ISSUE THREAD

**Issue by felahdab** [dotswan/filament-map-picker#30]
Hi.

Thank you for this very nice plugin.

I would like to extend it by including geoman-free, because I would like to offer the user the possibility to store complex geometries associated with the models.

I installed geoman, and added the following imports into index.js :
``` js
import "@geoman-io/leaflet-geoman-free";
import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css";
```
I rebuild successfully and deploy the assets (`artisan filament:assets`).

However, when I do that, the map object doesn't work properly (it displays something but the tiles are messed up)...

Do you have any suggestion on how to include geoman ?
Can you direct me in the right direction ?

Regards.
Florian.

**Comment by felahdab** [comment]
As a complement: when I include only the first import and leave the css out, the map displays normaly, and I can see the geoman toolbar on the side, even if the display is messed up.

If anyone has an idea on how to make it right...

Thanks.

**Comment by mohaphez** [comment]
Hi @felahdab 
Could you share your code example in github repository ? or pushed here in separate branch,
I will check it

**Comment by felahdab** [comment]
Hi.

Thank you for your interest.

PR #31 includes the basic modifications I was hoping would suffice to include geoman into the leaflet component.
I am aware that there will be additionnal work on the Livewire part of it, but I would need your help on the javascript part firt.

Regards.

**Comment by vitormicillo** [comment]
> As a complement: when I include only the first import and leave the css out, the map displays normaly, and I can see the geoman toolbar on the side, even if the display is messed up.
> 
> If anyone has an idea on how to make it right

I have the same issue, with geoman library the tiles has a strange behaviour and all layout mess.

**Comment by felahdab** [comment]
Hi. 
I haven't had time to research more. But I have found that importing the geoman css file into the resources/css/index.css file resolves the tile messed up problem:
```js
resources/css/index.css: 

import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css";

resources/js/index.js: 
import * as L from 'leaflet';
import 'leaflet-fullscreen';
import "leaflet/dist/leaflet.css";
import "@geoman-io/leaflet-geoman-free";

```

Give it a try. 

Nevertheless, there are some significant changes to introduce in order to take advantage of the geoman features. I guess I would be better to create a new component (or package or plugin) entirely.

Regards.

**Comment by vitormicillo** [comment]
> Hi. I haven't had time to research more. But I have found that importing the geoman css file into the resources/css/index.css file resolves the tile messed up problem:
> 
> ```js
> resources/css/index.css: 
> 
> import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css";
> 
> resources/js/index.js: 
> import * as L from 'leaflet';
> import 'leaflet-fullscreen';
> import "@geoman-io/leaflet-geoman-free";
> ```
> 
> Give it a try.
> 
> Nevertheless, there are some significant changes to introduce in order to take advantage of the geoman features. I guess I would be better to create a new component (or package or plugin) entirely.
> 
> Regards.

Looks promisor, I will try this solution
Have you updated your PR with this solution ?
