### ISSUE TITLE
Update map location (Help)

### ISSUE THREAD

**Issue by vitormicillo** [dotswan/filament-map-picker#38]
Hi mate, very nice update 
I am thinking about how you used Action as an example to update the location of the marker on the map.
It should be inserted in the Create page with the header actions ?

```php

use Filament\Forms\Components\Actions\Action;
use Filament\Forms\Components\Actions;
use Filament\Support\Enums\VerticalAlignment;

Actions::make([
    Action::make('Set Default Location')
        ->icon('heroicon-m-map-pin')
        ->action(function (Set $set, $state, $livewire): void {
            $set('location', ['lat' => '52.35510989541003', 'lng' => '4.883422851562501']);
            $set('latitude', '52.35510989541003');
            $set('longitude', '4.883422851562501');
            $livewire->dispatch('refreshMap');
        })
])->verticalAlignment(VerticalAlignment::Start);
```

**Comment by mohaphez** [comment]
Hi @vitormicillo 

You can insert the action in the middle of your form inputs, specifically within the $form->schema([]) array, at any point where you'd like it to appear.

If you encounter any issues or need further assistance, feel free to let me know!
