### ISSUE TITLE
CSS and JavaScript appear on all pages

### ISSUE THREAD

**Issue by brianalviano** [dotswan/filament-map-picker#41]
![image](https://github.com/user-attachments/assets/94ee46f1-8c6b-4afa-9c36-269ebca61a50)
![image](https://github.com/user-attachments/assets/e66afd36-9f6f-4235-9722-13eed1818277)

This css and javascript always load on all pages even if I don't use the Map Picker.

Please see this documentation on the Filament website :
https://filamentphp.com/docs/3.x/support/assets#lazy-loading-javascript

**Comment by mohaphez** [comment]
Hello @brianalviano,

Due to dependencies, this approach isn’t working as expected. If you have any ideas or can suggest improvements, please feel free to submit a PR—we would warmly welcome it and be delighted to review it!

Thank you in advance for your efforts!
