### ISSUE TITLE
Using this plugin breaks another plugins javascript

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [dotswan/filament-map-picker#53]
Hello,

I am using another plugin and using this map picker plugin breaks its javascript with error
`Uncaught TypeError: L is not a function`
I am guessing it is because of this https://github.com/dotswan/filament-map-picker/blob/master/resources/js/index.js#L1
Would it be possible to change it to, for example, Leaflet?

Thank you!

**Comment by mohaphez** [comment]
Hello @dmitrijsmihailovs,

Just a heads-up that in the new version, the Leaflet alias has been updated from L to LF.

If you encounter any issues or have questions, feel free to reach out I’ll be happy to assist!
