### ISSUE TITLE
Default Location Button

### ISSUE THREAD

**Issue by saelco** [dotswan/filament-map-picker#8]
Hi,
Can a Default Location button be added? For example, I save a location point, say lat:xxxx and long:yyyy, and make it the default location in the database. Then, I edit that data and move the map location to lat:mmmm and long:nnnn. If I want to return to the default location without refreshing the page, I'll find it difficult, so I need a button to do that.

**Comment by mohaphez** [comment]
Hi Dear @saelco 

Certainly! After merging #5 and releasing the new version, you'll be able to update the map using the refreshMap() event. Below is an example code snippet:

![image](https://github.com/dotswan/filament-map-picker/assets/20874565/5b3e8cd4-be0a-43a0-8b90-45f38c347b99)

![image](https://github.com/dotswan/filament-map-picker/assets/20874565/1bf7a571-4bd8-4a61-a326-e51f2627c860)


Should you have any further suggestions, please do not hesitate to inform us. We warmly welcome them.

Thanks,

**Comment by saelco** [comment]
Thank you for the response that makes this plugin even better.
